### PR TITLE
Feature OS X Support

### PR DESCRIPTION
**Pull request by zenangst**
Fixes https://github.com/hyperoslo/Keychain/issues/6

### CODE REVIEW

**Comment by vadymmarkov** [comment]
@zenangst Don't we need to update podspec?

**Comment by zenangst** [comment]
Oh shit, forgot about that! Nice catch.

**Comment by zenangst** [comment]
@vadymmarkov should be good meow!

**Comment by vadymmarkov** [comment]
@zenangst :+1:

**Pull request merged**
